apiVersion: batch/v1
kind: Job
metadata:
  name: olac-init
spec:
  template:
    metadata:
      name: olac-init
      labels:
          app: olac
    spec:
      restartPolicy: Never
      containers:
        - name: olacdb-builder
          image: haepal/olac:db-5
          command: ['/init.sh', '/olac_schema.sql']
          volumeMounts:
            - name: olacdb
              mountPath: /db
        - name: dir-builder
          image: alpine
          command: ['mkdir', '-p', '/d/static', '/d/static-records', '/d/xmldump']
          volumeMounts:
            - name: olacdata
              mountPath: /d
      volumes:
        - name: olacdb
          persistentVolumeClaim:
              claimName: olacdb-pvc
        - name: olacdata
          persistentVolumeClaim:
              claimName: olacdata-pvc
