apiVersion: batch/v1
kind: Job
metadata:
  name: olac-init
spec:
  template:
    metadata:
      name: olac-init
      labels:
          app: olac
    spec:
      containers:
        - name: olacdb-builder
          image: haepal/olac:db-4
          command: ['/init.sh', '/olac_schema.sql']
            volumeMounts:
              - name: olacdb
                mountPath: /db
        - name: dir-builder
          image: alpine
          command: ['mkdir', '-p', '/d/static', '/d/static-records', '/d/xmldump']
            volumeMounts:
              - name: olacdata
                mountPath: /d
