apiVersion: apps/v1
kind: Deployment
metadata:
    name: olac
spec:
    template:    
        metadata:
            name: olac
            labels:
                app: olac
        spec:
            initContainers:
                - name: olacdb-builder
                  image: haepal/olac:db-3
                  command: ['/init.sh', '/olac_schema.sql']
                  volumeMounts:
                      - name: olacdb
                        mountPath: /db
                - name: dir-builder
                  image: alpine
                  command: ['mkdir', '/d/static', '/d/static-records', '/d/xmldump']
                  volumeMounts:
                      - name: olacdata
                        mountPath: /d
            containers:
                - name: olacdb
                  image: haepal/olac:db-3
                  command: ['mysqld', '--user=mysql', '--datadir=/db', '--skip-networking=false']
                  volumeMounts:
                      - name: olacdb
                        mountPath: /db
                - name: olacweb
                  image: haepal/olac:web-1
                  volumeMounts:
                      - name: olacdata
                        mountPath: /olac/web/data
            volumes:
                - name: olacdb
                  persistentVolumeClaim:
                      claimName: olacdb-pvc
                - name: olacdata
                  persistentVolumeClaim:
                      claimName: olacdata-pvc
    selector:
        matchLabels:
            app: olac
