apiVersion: apps/v1
kind: Deployment
metadata:
  name: olac
spec:
  selector:
    matchLabels:
      app: olac
  template:
    metadata:
      name: olac
      labels:
        app: olac
    spec:
      initContainers:
      - name: dir-builder
        image: alpine
        command: ['mkdir', '-p', '/d/static', '/d/static-records', '/d/xmldump']
        volumeMounts:
          - name: olacdata
            mountPath: /d
      containers:
      - name: olacdb
        image: haepal/olac:db-11
        volumeMounts:
        - name: olacdb
          mountPath: /var/lib/mysql
        resources:
          requests:
            cpu: "0.5"
            memory: 500Mi
          limits:
            cpu: "1"
            memory: 2Gi
        envFrom:
        - configMapRef:
            name: olac-config
          prefix: OLAC_
        - secretRef:
            name: olac-secret
          prefix: OLAC_
        - secretRef:
            name: mysql-root
      - name: olacweb
        image: haepal/olac:web-17
        volumeMounts:
        - name: olacdata
          mountPath: /olac/web/data
        resources:
          requests:
            cpu: "0.5"
            memory: 500Mi
          limits:
            cpu: "1"
            memory: 2Gi
      volumes:
      - name: olacdb
        persistentVolumeClaim:
          claimName: olacdb-pvc
      - name: olacdata
        persistentVolumeClaim:
          claimName: olacdata-pvc
