apiVersion: apps/v1
kind: Deployment
metadata:
    name: olac
spec:
    template:
        metadata:
            name: olac
            labels:
                app: olac
        spec:
            initContainers:
                - name: olacdb-builder
                  image: haepal/olac:db-3
                  command: ['/init.sh', '/olac_schema.sql']
                  volumeMounts:
                      - name: olacdb
                        mountPath: /db
            containers:
                - name: olacdb
                  image: haepal/olac:db-3
                  command: ['mysqld', '--user=mysql', '--datadir=/db', '--skip-networking=false']
                  volumeMounts:
                      - name: olacdb
                        mountPath: /db
            volumes:
                - name: olacdb
                  persistentVolumeClaim:
                      claimName: olacdb-pvc
    selector:
        matchLabels:
            app: olac