apiVersion: apps/v1
kind: Deployment
metadata:
    name: olac
spec:
    template:    
        metadata:
            name: olac
            labels:
                app: olac
        spec:
            containers:
                - name: olacdb
                  image: haepal/olac:db-4
                  command: ['mysqld', '--user=mysql', '--datadir=/db', '--skip-networking=false']
                  volumeMounts:
                      - name: olacdb
                        mountPath: /db
                - name: olacweb
                  image: haepal/olac:web-9
                  volumeMounts:
                      - name: olacdata
                        mountPath: /olac/web/data
            volumes:
                - name: olacdb
                  persistentVolumeClaim:
                      claimName: olacdb-pvc
                - name: olacdata
                  persistentVolumeClaim:
                      claimName: olacdata-pvc
    selector:
        matchLabels:
            app: olac
