---
apiVersion: v1
kind: Secret
metadata:
  name: olac-secret
type: Opaque
data:
  MYSQL_PASSWORD: b2xhYzEyMw==

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: NzNxdzBEc3lQdUd5TU0=
