#! /bin/sh

echo "Check if ISO 639-3 Retirements table is current..."

URL="http://www-01.sil.org/iso639-3/iso-639-3_Retirements.tab"
CHKSUM="3bc68c617f2e5afbd680b3ac4d304081"

NEW_CHKSUM=$(curl -s -L "$URL" | md5sum | cut -d' ' -f 1)

if [ "$NEW_CHKSUM" = "$CHKSUM" ]; then
    echo PASS
else
    echo FAIL
fi
