#! /bin/sh

echo "Check if Ethnologue LanguageCodes.tab is current..."

URL="http://www.ethnologue.com/codes/LanguageCodes.tab"
CHKSUM="d5e741a7c67cd3fd82538bdbeb08de12"

NEW_CHKSUM=$(curl -s -L "$URL" | md5sum | cut -d' ' -f 1)

if [ "$NEW_CHKSUM" = "$CHKSUM" ]; then
    echo PASS
else
    echo FAIL
fi
