#! /bin/sh

echo "Check if DC schema has not changed..."

URL="http://dublincore.org/schemas/xmls/qdc/2006/01/06/dc.xsd"
CHKSUM="f3fa7880f6fac5c76e6ae5f236833d8e"

NEW_CHKSUM=$(curl -s "$URL" | md5sum | cut -d' ' -f 1)

if [ "$NEW_CHKSUM" = "$CHKSUM" ]; then
    echo YES
else
    echo NO
fi
