#! /bin/sh

echo "Check if Ethnologue LanguageCodes.tab is current..."

URL="http://www.ethnologue.com/codes/LanguageCodes.tab"
CHKSUM="2b4b75598d9c79ae53495b8582a8159e"

NEW_CHKSUM=$(curl -s -L "$URL" | md5sum | cut -d' ' -f 1)

if [ "$NEW_CHKSUM" = "$CHKSUM" ]; then
    echo PASS
else
    echo FAIL
fi
