#! /bin/sh

echo "Check if DCMIType schema has not changed..."

URL="http://dublincore.org/schemas/xmls/qdc/2006/01/06/dcmitype.xsd"
CHKSUM="f3a01f32230e6af6e22732121502c0b0"

NEW_CHKSUM=$(curl -s "$URL" | md5sum | cut -d' ' -f 1)

if [ "$NEW_CHKSUM" = "$CHKSUM" ]; then
    echo YES
else
    echo NO
fi
