#! /bin/sh

echo "Check if dcterms schema has not changed..."

URL="http://dublincore.org/schemas/xmls/qdc/dcterms.xsd"
CHKSUM="e4adbcd86097cf5e03aab66912235c68"

NEW_CHKSUM=$(curl -s "$URL" | md5sum | cut -d' ' -f 1)

if [ "$NEW_CHKSUM" = "$CHKSUM" ]; then
    echo PASS
else
    echo FAIL
fi
