#! /bin/sh

echo "Check if simple DC schema has not changed..."

URL="http://dublincore.org/schemas/xmls/qdc/2006/01/06/simpledc.xsd"
CHKSUM="ff24acd43883f78f26a71ff8e5dd42b4"

NEW_CHKSUM=$(curl -s "$URL" | md5sum | cut -d' ' -f 1)

if [ "$NEW_CHKSUM" = "$CHKSUM" ]; then
    echo YES
else
    echo NO
fi
