#! /bin/sh

echo "Check if ISO 639-3 table is current..."

URL="http://www-01.sil.org/iso639-3/iso-639-3.tab"
CHKSUM="249362f2663c0c0676b5a75f73597f7c"

NEW_CHKSUM=$(curl -s -L "$URL" | md5sum | cut -d' ' -f 1)

if [ "$NEW_CHKSUM" = "$CHKSUM" ]; then
    echo PASS
else
    echo FAIL
fi
