#! /bin/sh

echo "Check if dcterms schema has not changed..."

URL="http://dublincore.org/schemas/xmls/qdc/2006/01/06/dcterms.xsd"
CHKSUM="1ce17fa25b9537f079cc9fe90f8d19f4"

NEW_CHKSUM=$(curl -s "$URL" | md5sum | cut -d' ' -f 1)

if [ "$NEW_CHKSUM" = "$CHKSUM" ]; then
    echo PASS
else
    echo FAIL
fi
