#! /bin/sh

echo "Check if ISO 639-3 table is current..."

URL="http://www-01.sil.org/iso639-3/iso-639-3.tab"
CHKSUM="b8cf6d94a614a25790012c53ae2fcaa1"

NEW_CHKSUM=$(curl -s -L "$URL" | md5sum | cut -d' ' -f 1)

if [ "$NEW_CHKSUM" = "$CHKSUM" ]; then
    echo PASS
else
    echo FAIL
fi
