#! /bin/sh

echo "Check if mysql accepts connection..."

user=$(olacvar mysql/user)
pw=$(olacvar mysql/passwd)
db=$(olacvar mysql/olacdb)
host=$(olacvar mysql/host)
echo "show tables" | mysql -q -h $host -u $user -p$pw $db >/dev/null 2>&1

if [ $? -eq 0 ]; then
	echo YES
else
	echo NO
fi

