#! /bin/bash

case ${0##*_} in
    dev)
        version="dev server"
        DLA_URL="http://syslsl01.library.upenn.edu/dla/olac/search.html?q="
        ;;
    *)
        version="production server"
        DLA_URL="http://dla.library.upenn.edu/dla/olac/search.html?q="
        ;;
esac

echo -n "Check DLA OLAC catalog's size ($version)... "

THRESHOLD=200

get_num_dla_records() {
    curl -s "$1" 2>/dev/null | grep 'out of' | sed -r 's/[^0-9]*([0-9]+).*/\1/'
}

get_num_olac_records() {
    user=$(olacvar mysql/user)
    pw=$(olacvar mysql/passwd)
    db=$(olacvar mysql/olacdb)
    host=$(olacvar mysql/host)
    echo "select count(*) from ARCHIVED_ITEM" |
        mysql -h $host -u $user -p"$pw" $db 2>/dev/null |
        sed 1d
}

n=$(get_num_olac_records)
m=$(get_num_dla_records $DLA_URL)

if [[ -z $n || -z $m ]]; then
    echo
    echo ERROR
    exit 1
fi

d=$(($m - $n))

if [[ ${d#-} -lt $THRESHOLD ]]; then
    echo "(|$m - $n| < $THRESHOLD)"
    echo PASS
else
    echo "(|$m - $n| >= $THRESHOLD)"
    echo FAIL
fi

