python harvester.py -c ~/oai.my.cnf -s http://animaldiversity.ummz.umich.edu/local/oai/do
python harvester.py -c ~/oai.my.cnf -s http://phy043.tours.inra.fr:8080/perl/oai2
python harvester.py -c ~/oai.my.cnf -s http://www.genlit.org/agr/oai/
python harvester.py -c ~/oai.my.cnf -s http://cgi.vtt.fi/progs/inf/balticOAI
python harvester.py -c ~/oai.my.cnf -s http://www.biomedcentral.com/oai/2.0/
python harvester.py -c ~/oai.my.cnf -s http://caltechcdstr.library.caltech.edu/perl/oai2
python harvester.py -c ~/oai.my.cnf -s http://caltecheerl.library.caltech.edu/perl/oai2
python harvester.py -c ~/oai.my.cnf -s http://caltechgalcitfm.library.caltech.edu/perl/oai2
python harvester.py -c ~/oai.my.cnf -s http://caltechlessgs.library.caltech.edu/perl/oai2
python harvester.py -c ~/oai.my.cnf -s http://caltechparadise.library.caltech.edu/perl/oai2
python harvester.py -c ~/oai.my.cnf -s http://cemi.socionet.ru/oai/ecoorg:org1/oai.cgi
python harvester.py -c ~/oai.my.cnf -s http://ir.lib.cbs.dk/oai.php
python harvester.py -c ~/oai.my.cnf -s http://www.dmg-lib.org/dmglib/OAI-2.0-Server
python harvester.py -c ~/oai.my.cnf -s http://dspace.hsl.washington.edu/dspace-oai/request
python harvester.py -c ~/oai.my.cnf -s http://publications.sckcen.be/dspace-oai/request
python harvester.py -c ~/oai.my.cnf -s http://europeangovernance.livingreviews.org/register/oai
python harvester.py -c ~/oai.my.cnf -s http://relativity.livingreviews.org/register/oai
python harvester.py -c ~/oai.my.cnf -s http://solarphysics.livingreviews.org/register/oai
python harvester.py -c ~/oai.my.cnf -s http://petroleumjournalsonline.com/journals/index.php/index/oai/
python harvester.py -c ~/oai.my.cnf -s http://www.sugarresearch.library.qut.edu.au/perl/oai2
python harvester.py -c ~/oai.my.cnf -s http://ws.pangaea.de/oai/
